[tool.commitizen]
version_scheme = "semver"
version = "1.0.1"
version_files = [
    "PrimerStripeSDK/Sources/Version/Version.swift:let PrimerStripeSDKVersion",
    "PrimerStripeSDK.podspec:spec.version",
]
